# Site Options
title:      UoB eSports
caption:    We are the University of Brighton eSports Society
url:        http://uobesports.com
email:      oliver@uobesports.com
feedburner: http://feeds.feedburner.com/uobesports
analytics:  UA-20955831-8
share:      ra-5500c8be4c6071e1

elsewhere:
- name: Twitter
  link: //twitter.com/UoBeSports
  desc: Follow @UoBeSports on Twitter
- name: Subscribe to feed
  link: /feed/
  desc: Subscribe to the website's Atom feed
- name: Subscribe by email
  link: http://feedburner.google.com/fb/a/mailverify?uri=uobesports
  desc: Subscribe to email updates
- name: Teamspeak
  link: //649513.ts3.mpgs.co
  desc: The UoB eSports Teamspeak server
- name: Email Us
  link: "mailto:oliver@uobesports.com"
  desc: Get in touch
# - name: Sponsor us
#   link: /sponsors/
#   desc: Sponsor the University of Brighton eSports Society or Teams

# Jekyll Options
safe:        true
baseurl:     /

source:      .
destination: /tmp/esports
exclude:
- bin
- Makefile
- README.md
future:      true
timezone:    UCT
lsi:         false
markdown:    kramdown
permalink:   /:title/
